version: 2.1

jobs:
  build:
    executor:
      name: windows/default

    steps:
      - checkout

      - run:
          name: Install .NET 10 SDK
          command: choco install dotnet-sdk --version=10.0.100-preview -y

      - run:
          name: Restore
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --configuration Release --no-restore

      - run:
          name: Publish
          command: dotnet publish -c Release -r win-x64 --self-contained false -o publish

workflows:
  build_workflow:
    jobs:
      - build
